# Elemanları 0 lardan oluşan array oluşturmak

In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros(10,dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

#elemanları 0 lardan oluşan multidimensional array oluşturmak 

In [4]:
# 3 row(satır) ve 4 column(sütun)' u olan bir array oluşturmak
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
#3 tane 8'lik 
np.zeros([3,8,8])


array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0

In [6]:
#normalde float yaratıyor ama data tipini kendimiz belirtebiliriz.
np.zeros(2, dtype=int)

array([0, 0])

In [7]:
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [8]:
x=np.zeros([3,8,8,5])

In [9]:
x

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],



In [11]:
x=np.array([1,2,3,4,-8,-10],dtype=float)
print(x[::-1])  #tersten yazdırır.

[-10.  -8.   4.   3.   2.   1.]


# Belirtilen bir elemandan array oluşturmak

In [12]:
np.full((4,5),5)    #4*5'lik 5 elemanından oluşan array

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [14]:
np.full(4,5)

array([5, 5, 5, 5])

In [15]:
np.full((4,5),"a")

array([['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a']], dtype='<U1')

# ardışık sayılardan array oluşturmak

In [16]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
np.arange(2,12,-2) #küçükten büyüğe ters gidemez, hata verir. 

array([], dtype=int32)

In [19]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [20]:
np.arange(12,2,-2)

array([12, 10,  8,  6,  4])

# aralığı eşit uzaklıktaki noktalara bölmek

-belirlenen başlangıç ve bitiş değerine göre, başlangıcı ve bitişi de alarak eşit uzaklıkta noktalara bölmek.

In [22]:
np.linspace(1,2,3) #1 ve 2 dahil 3 noktaya bölmek

array([1. , 1.5, 2. ])

In [23]:
np.linspace(0,1,30) #0 ve 1 dahil 30 parça

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [24]:
np.linspace(1,2,3, endpoint=False) #1 dahil 2 dahil değil 3 nokta

array([1.        , 1.33333333, 1.66666667])

In [25]:
np.linspace(1.5,4.7,3) #float tipini de destekler.

array([1.5, 3.1, 4.7])

# Normal dağılımdan çekilmiş değerler ile array oluşturmak

(mean,std, array size) = ortalama, std sapma, kaça kaçlık array 

In [26]:
np.random.normal(0,1,(4,5))  #ortalaması 0, std sapması 1 olan 4*5' lik array

array([[-0.56434874,  0.40877097,  2.53749612, -0.40725346, -1.0563668 ],
       [-0.29435529, -1.68100347, -0.86689882, -0.38587311,  0.09086964],
       [-1.73823215,  1.34229866,  0.76354897,  0.18488963, -1.09598364],
       [-2.12681285,  0.65423511, -0.48735495,  1.85786973,  0.3598197 ]])

In [28]:
np.random.normal(0,100,(4,5)) # ort 0, std sapma 100 olan 4*5'lik array

array([[  12.42052566,   38.50888165,    2.57837871, -190.75713367,
        -169.60766589],
       [  35.54603056,   74.45025123,  126.56577963,   51.13454236,
         -66.95871441],
       [ 194.74943917,  -39.15766995,  -51.14060404, -168.35437316,
        -289.0281178 ],
       [ -83.12763354,  -52.9849855 ,    5.71457072,   18.05854562,
          20.10317249]])

# random integerlardan oluşan array oluşturmak

In [29]:
np.random.randint(1,10,(3,4)) #1 ve 10 arasında 3*4' lük array 

array([[7, 8, 6, 5],
       [6, 2, 8, 9],
       [9, 9, 4, 7]])

In [31]:
np.random.randint(1,10,(3,5,5))  #1 ile 10 arasında 3 tane 5*5' lik array

array([[[4, 9, 5, 3, 5],
        [6, 1, 7, 8, 8],
        [7, 6, 9, 7, 5],
        [2, 3, 2, 3, 6],
        [6, 8, 2, 8, 6]],

       [[1, 6, 8, 6, 1],
        [2, 6, 1, 1, 4],
        [4, 3, 3, 7, 9],
        [6, 5, 8, 1, 1],
        [3, 1, 6, 7, 7]],

       [[6, 6, 9, 8, 5],
        [1, 5, 3, 8, 2],
        [7, 3, 7, 3, 2],
        [9, 9, 6, 7, 5],
        [7, 9, 6, 8, 9]]])

In [32]:
np.random.randint(1,2)

1

# Identity(birim)  Matrix oluşturmak

In [33]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [35]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# array işlemleri

In [36]:
[2,4,8]*3

[2, 4, 8, 2, 4, 8, 2, 4, 8]

In [37]:
[2,4,8]+[2,4,8]+[2,4,8]

[2, 4, 8, 2, 4, 8, 2, 4, 8]

In [38]:
#pythonda listeler arasında * işlemi tanımlı değilken; * operatörü iki numpy arrayi arasında tanımlıdır.
x=np.array([1,2,3])
y=np.array([3,4,5])

x*y

array([ 3,  8, 15])

In [39]:
#elemanlar çarğıldığı için eleman sayıları eşit olmalıdır. 

In [40]:
x+y   # + operatörü pythonda listeleri birleştirirken, burada elemanları toplar. 

array([4, 6, 8])

# array attribute(ana başlık)

# shape 

In [41]:
x=np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [42]:
y=np.zeros((2,4,5))
print(y)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [43]:
x.shape

(2, 3)

In [44]:
y.shape

(2, 4, 5)

In [ ]:
#.shape arrayların kaça kaç olduğunu verir.

# ndim

In [45]:
x.ndim

2

In [46]:
y.ndim

3

In [47]:
#.ndim boyutu verir.


# size

In [48]:
x.size

6

In [49]:
#kaç elemanlı olduğunu döndürür.

In [50]:
y.size

40

# dtype

In [51]:
#incelenen arrayin veri tipi.

In [52]:
x.dtype

dtype('float64')

In [53]:
y.dtype

dtype('float64')

# reshaping

In [54]:
#eldeki arrayin başka bir şekilde ifade edilmesini sağlar. 

In [55]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
a.ndim

1

In [57]:
a.size

10

In [58]:
a.reshape(2,5) #a'yı 2*5' lik şekilde ifade et. 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [59]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

#eleman sayıları tutmazsa hata verir.

# -1 ile  boyuta karar vermek

In [63]:
#-1 arkaplanda kendisi hesaplayıp değeri belirler. yanında 2 varsa 10 elemanlı bir veriyse otomatik 5 yazar.

In [62]:
a.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# concatenation

-amaç iki arrayi birleştirmek.

In [ ]:
#python da + operatörü ile yapılan concat işlemi.

In [64]:
a=np.array([1,2,3,4])

In [65]:
b=np.array([5,6,7,8])

In [66]:
a

array([1, 2, 3, 4])

In [67]:
b

array([5, 6, 7, 8])

In [69]:
np.concatenate([a,b])   #a ve b yi birleştir.

array([1, 2, 3, 4, 5, 6, 7, 8])

In [71]:
l=[10,11,11.2]  #liste ve array de concat olabilir.


In [72]:
np.concatenate([a,b,l])

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. , 10. , 11. , 11.2])

In [74]:
t=(10,11)   #python tuple

In [76]:
np.concatenate([a,b,t])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

# size mismatch

In [77]:
a

array([1, 2, 3, 4])

In [78]:
x=np.array([[1,2,3],
          [4,5,6]])

In [79]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
x.size

6

In [81]:
x.shape

(2, 3)

In [82]:
a.shape  

(4,)

In [84]:
np.concatenate([x,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [86]:
np.concatenate([x,x],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [87]:
#axis ile birleştireceği doğruyu belirler. 

# Stack

In [91]:
#stack yeni bir dimension yarat üzerine birleştir. 

In [88]:
np.stack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [89]:
np.stack([a,b],axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [90]:
np.stack([a,b]).shape

(2, 4)

In [2]:
import numpy as np

In [3]:
 np.zeros((3,3,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [95]:
#hackerrank soru denemesi
a=np.zeros((3,3,3),dtype=int)
print(a)
b=np.ones((3,3,3),dtype=int)
print(b)      



[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# Splitting

In [4]:
l=[10,20,30,40,50,60,70,80]
l

[10, 20, 30, 40, 50, 60, 70, 80]

In [7]:
np.split (l,[2,6])  #2.indexle 6.index arasında çizgi yok oluşan aralıkları döndür.

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [10]:
np.split(l,[3,5])

[array([10, 20, 30]), array([40, 50]), array([60, 70, 80])]

In [11]:
a=np.array([10,20,30,40])

In [12]:
np.split(a,[2,6])

[array([10, 20]), array([30, 40]), array([], dtype=int32)]

# splitin sonucunu birden çok değişkene eşitleme

In [13]:
a,b=(1,10)

In [14]:
print(a)
print(b)

1
10


In [16]:
x,y,z=np.split(l,[2,6])

In [17]:
print(x)
print(y)
print(z)

[10 20]
[30 40 50 60]
[70 80]


# vsplit

Satır odaklı böler.

In [18]:
a=np.arange(20).reshape(2,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [19]:
np.vsplit(a,[1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [20]:
np.vsplit(a,[1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [29]:
b=np.arange(20).reshape(5,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [30]:
np.vsplit(b,[2,3])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

# hsplit

sütun odaklı böler.

In [21]:
np.hsplit(a,[2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [22]:
np.hsplit(a,[2])[0]

array([[ 0,  1],
       [10, 11]])

In [23]:
np.hsplit(a,[2])[1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [24]:
x,y,x=np.hsplit(a,[2,4])#2.indexin başına ve 4.indexin başına bir çizgi koy. 3 tane array olusur.
print(x)
print(y)
print(z)

[[ 4  5  6  7  8  9]
 [14 15 16 17 18 19]]
[[ 2  3]
 [12 13]]
[70 80]


# Sorting

sıralama yapılacağı zaman

In [32]:
a=np.array([20,32,5,7])
np.sort(a)

array([ 5,  7, 20, 32])

# argsort

Sıralar, sıraladıktan sonra indexlerini verir.

In [34]:
np.argsort(a)

array([2, 3, 0, 1], dtype=int64)

# multidimensional arraylerin elemanların ulaşmak

In [35]:
a=np.arange(1,21).reshape(4,5)

In [36]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [43]:
a[0]    #axis=0 satır, axis=1 sütun bu işlem önce axis= 0 da işlem yapıyor yanı satır odaklı döndürür.

array([1, 2, 3, 4, 5])

In [38]:
a[1]

array([ 6,  7,  8,  9, 10])

In [39]:
a[0,0]

1

In [40]:
a[0][0]

1

In [41]:
a[1][1]

7

In [42]:
a.ndim

2

In [44]:
a[1,1]=10 #1,1 deki yeri 10 yap

In [45]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [46]:
a[1,1]=30.5   #floatı int yapıyor.

In [47]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 30,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [50]:
a[1,1]="2"  #stringi int çevirir. "30.5" da hata verir çünkü stringden float float dan int çeviremez.
a 

array([[ 1,  2,  3,  4,  5],
       [ 6,  2,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# slice indexing

In [51]:
a=np.arange(1,21).reshape(4,5)

In [60]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [52]:
a[1]

array([ 6,  7,  8,  9, 10])

In [53]:
a[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [54]:
a[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [55]:
a[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [56]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [58]:
a[1::2]   #başlangıç, bitiş, adım sayısı

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [59]:
a[:,3]  

array([ 4,  9, 14, 19])

In [61]:
a[::2,3]  

array([ 4, 14])

In [62]:
a[0,:]

array([1, 2, 3, 4, 5])

In [63]:
a[0]

array([1, 2, 3, 4, 5])

In [64]:
a[0:2,4]   #0.satırın 2 den başla 4. indexde bitir.

array([ 5, 10])

In [65]:
a[::,:4]  #sonuncu sütunu almaz.

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

# Fancy ındexing

Şimdiye kadar hep belirli elemanlar, belirli grupları alabildik. Özellikle belirtilen elemanları nasıl döndürürüz?

In [66]:
x=np.arange(1,15)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
idxs=[4,5,7,11]   #almak istediğim değerlerin indexleri. Bu bir liste.

In [68]:
x[idxs]   

array([ 5,  6,  8, 12])

In [69]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
a[0:2,1]  #, den önceki değer satırda değişiklik yapar, sonraki sütunda.
#0 ve 2. satır arasında 1.sütunla birleşimi.

array([1, 5])

In [71]:
a[0:2,1].shape

(2,)

In [72]:
a[0:2,1:3].shape

(2, 2)

In [73]:
a[0:,[1,3]]  # bütün satırları tara 1.ve 3. sütun için

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [79]:
a=np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
idx1=[1,3,2]

In [75]:
idx2=[3,0,2]

In [80]:
a[idx1,idx2]   #îdx1 elemanları satırları, idx2 deki elemanlar sütunu ifade eder.

array([ 8, 15, 12])

Fancy indexing sonucunu belirli değerlere eşitlemek

In [83]:
x

array([ 1, 20, 20, 20,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [82]:
x[[1,2,3]]=20
x

array([ 1, 20, 20, 20,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [84]:
x=np.arange(9)

In [85]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [86]:
x[[1,2,5]]=[100,200,300]

In [87]:
x

array([  0, 100, 200,   3,   4, 300,   6,   7,   8])

In [88]:
#patika sorusu
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
a[1,(1,3)]

array([6, 8])

In [90]:
a[1,(1,3)].ndim   #boyut belirler.

1

In [91]:
a[1:,(1,3)]

array([[ 6,  8],
       [10, 12]])

In [92]:
a[1:,3]

array([ 8, 12])

In [94]:
a[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

# subarray

In [95]:
a=np.arange(1,21).reshape(4,5)

In [96]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [98]:
b=a[:2,:3]
b


array([[1, 2, 3],
       [6, 7, 8]])

In [99]:
b.ndim

2

In [100]:
b[0][0]=100
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [101]:
a   # b'yi değiştirince otoatik a da değişti. Aynı hafızaya bağlılar. 

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [102]:
#aynı anda değişmelerine engel olmak için .copy() kullan.
a=np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [103]:
b=a[:2,:3].copy()
b

array([[1, 2, 3],
       [6, 7, 8]])

In [104]:
b[0][0]=100
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [105]:
a  #copy sayesinde a değişmedi. Hafızada başka yer tutuyor. 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# Conditional Indexing

In [2]:
import numpy as np

durumları inceliyor.

In [3]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a<5 #boolean array oluşturur.

array([ True,  True,  True,  True, False, False, False, False, False])

In [5]:
a[a<5]  #koşulu sağlayanları verir.

array([1, 2, 3, 4])

In [8]:
filt=a<3

In [9]:
filt

array([ True,  True, False, False, False, False, False, False, False])

In [10]:
a[filt]

array([1, 2])

In [11]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
b=np.array([2,3,4,5,61,7,8,11])
b

array([ 2,  3,  4,  5, 61,  7,  8, 11])

In [18]:
(a<3) | (a>5)    #| operatörü or yerine geçer. 

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [19]:
a[(a<3) | (a>5)]

array([1, 2, 6, 7, 8, 9])

In [20]:
filt= (a<3) | (a>5) 
filt

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [21]:
a[filt]

array([1, 2, 6, 7, 8, 9])

In [23]:
a[(a>3) & (a<5)]   # ve operatörü

array([4])

-filtrelerin değerini yazarken ~ kullanılır.

# sum 

In [25]:
a=np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
np.sum(a)

210

In [27]:
filt = a<5 
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [29]:
np.sum(filt)   # true=1 false=0 olacak şekilde toplam 4 tane true var, sum=4

4

In [30]:
a[filt]

array([1, 2, 3, 4])

In [31]:
np.sum(a[filt])

10

In [32]:
filt= (a>5) & (a<9)
filt

array([[False, False, False, False, False],
       [ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [33]:
a[filt]

array([6, 7, 8])

# All

Tüm elemanlar şartı sağlıyor mu konntrol etmek.
np.all boolean. true yada false 
bütün hepsi true ise true döndürür. 

In [38]:
a=np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
a>-1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [40]:
np.all(a>-1)

True

In [41]:
np.all(a>5)

False

In [48]:
a>5

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [46]:
np.all(a>5,axis=1) #yatay bakar

array([False, False,  True,  True])

In [45]:
np.all(a>5,axis=0)

array([False, False, False, False, False])

In [49]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [50]:
a>8

array([[False, False, False, False, False],
       [False, False, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [51]:
np.all(a>8,axis=1)

array([False, False,  True,  True])

# any()

herhangi bir eleman verildiğinde şartı sağlıyor mu diye kontrol etmek.
herhangi biri true ise true döndürür.

In [52]:
a=np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [53]:
a>17

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True]])

In [54]:
np.any(a>17)

True

In [55]:
np.any(a>17,axis=0)

array([False, False, False,  True,  True])

In [56]:
np.any(a>17,axis=1)

array([False, False, False,  True])