In [1]:
import numpy as np

#numpy arrayler python list lerine benziyor ancak homojen( tek veri tipinde) elemanları olması gerekiyor.

# listlerden array yaratmak

In [2]:
x=np.array([1,2,3,4])

In [3]:
x

array([1, 2, 3, 4])

#integer ve float veri tipi birlikteyken bütün elemanlar float türünde yazılır. float daha genel.

In [6]:
b=np.array([1,2,3,4.5])

In [7]:
b

array([1. , 2. , 3. , 4.5])

In [8]:
#integer, float ve string için hepsi stringe dönüştürülür.
c=np.array([1,2,3,4.5,'2'])

In [9]:
c

array(['1', '2', '3', '4.5', '2'], dtype='<U32')

# array data tipini manuel olarak belirtmek

arrayin elemanlarının tipini kendimiz belirtebiliriz.

In [14]:
x= np.array([1,2,3,4.5])

In [15]:
x

array([1. , 2. , 3. , 4.5])

In [16]:
x=np.array([1,2,3,4.5], dtype="int32")

In [17]:
x

array([1, 2, 3, 4])

In [18]:
x=np.array([1,2,3,4.5], dtype="str")

In [19]:
x

array(['1', '2', '3', '4.5'], dtype='<U3')